CREATE DATABASE IF NOT EXISTS vueos;
CREATE USER 'vue-os' @'%' IDENTIFIED VIA mysql_native_password USING '***';
GRANT ALL PRIVILEGES ON *.* TO 'vue-os' @'%' REQUIRE NONE WITH
GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
USE vueos;
CREATE TABLE IF NOT EXISTS auth (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(30) NOT NULL,
    token VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS messaging (
    global_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sender INT NOT NULL,
    receiver INT NOT NULL,
    content LONGTEXT NOT NULL,
    chat_order INT NOT NULL
);